### PR TITLE
compile asm drivers for cyclone and drz80 on arm

### PR DESCRIPTION
**Pull request by markwkidd**
As @dankcushions suggested in https://github.com/libretro/mame2000-libretro/issues/40#issuecomment-312185221 this would use the assembly version of the drivers for these two cpus, as is done with mame4all.

Hopefully this will address the performance difference between mame2000 and mame4all on rPi boards, however I don't have any arm hardware to test this on. @herbfargus & @hizzlekizzle you also posted in the issue so I'm going to tag you here in case you have input on this PR.

### CODE REVIEW

**Comment by twinaphex** [comment]
@HerbFargus You'd like to test this first?

**Comment by HerbFargus** [comment]
@dankcushions probably has a better handle on the differences between the two as it's been a while since I've messed with mame but I'll try to look into it when I get a chance

**Comment by twinaphex** [comment]
@dankcushions You want to have the honor of testing this then?

**Comment by dankcushions** [comment]
will try and test tonight!

**Comment by HerbFargus** [comment]
I just gave it a quick glance on my pi 3 but I couldn't find any games that had a noticeable enough slowdown to test with, will probably be easier to see if I test on my pi 1 or 0 . Which games would be the best to test with?

**Comment by dankcushions** [comment]
@HerbFargus FYI you'd need to test games that use the Z80 and 68k cpu driver. i'm not sure of any that slowdown either, but i guess if they at least run it means that the ASM is working fine.

**Comment by twinaphex** [comment]
@dankcushions Thanks for wanting to test it.

**Comment by dankcushions** [comment]
getting a build error. suspect this is to do with other recent commits, though: 

```src/libretro/fileio.c: In function ‘create_path_recursive’:
src/libretro/fileio.c:356:10: error: ‘errno’ undeclared (first use in this function)
   return errno;
          ^
src/libretro/fileio.c:356:10: note: each undeclared identifier is reported only once for each function it appears in
Makefile:363: recipe for target 'src/libretro/fileio.o' failed
```

**Comment by markwkidd** [comment]
@r-type I think it's part of your new code

**Comment by r-type** [comment]
The last pr fixed this issue. Please update your repo and build again :)

**Comment by dankcushions** [comment]
yep, latest master works! Just need @markwkidd to update their repo so I can test.

**Comment by markwkidd** [comment]
@dankcushions things should sync'd now in my "patch-1" branch if you try again. thank you

**Comment by dankcushions** [comment]
build error:
```
src/cpu/z80_drz80/drz80.s -osrc/cpu/z80_drz80/drz80.o
src/cpu/z80_drz80/drz80.s: Assembler messages:
src/cpu/z80_drz80/drz80.s:4085: Error: swp{b} use is obsoleted for ARMv8 and later
src/cpu/z80_drz80/drz80.s:4087: Error: swp{b} use is obsoleted for ARMv8 and later
src/cpu/z80_drz80/drz80.s:5141: Error: swp{b} use is obsoleted for ARMv8 and later
src/cpu/z80_drz80/drz80.s:5143: Error: swp{b} use is obsoleted for ARMv8 and later
src/cpu/z80_drz80/drz80.s:5145: Error: swp{b} use is obsoleted for ARMv8 and later
Makefile:366: recipe for target 'src/cpu/z80_drz80/drz80.o' failed
make: *** [src/cpu/z80_drz80/drz80.o] Error 1
```
we've had this error before... https://github.com/RetroPie/RetroPie-Setup/issues/1317

looks like solutions could be
* compiling as armv7  - https://github.com/RetroPie/RetroPie-Setup/commit/0fcb5554d62b6eeb79b4b5a9d734e48ce243bd5d
* making a change to the asm: https://github.com/RetroPie/RetroPie-Setup/issues/1317#issuecomment-272658999

i guess the latter is preferable, if it works.

**Comment by markwkidd** [comment]
@dankcushions I implemented the proposed patch from https://github.com/RetroPie/RetroPie-Setup/issues/1317#issuecomment-272658999

Is there a way for me to cross-compile this? I hate to keep asking you to compile

**Comment by dankcushions** [comment]
I think jools does it for retropie, also this might help: https://github.com/mupen64plus/mupen64plus-core/issues/96#issuecomment-329108352

but really i don't mind!

in any case, i re-built and it - compiles fine! and my two test games: bublbobl (z80) and sf2 (68k), worked fine! so from my testing i think this should be good to go - thanks!

**Comment by markwkidd** [comment]
Nice! @twinaphex I think this is ready to merge now.

**Comment by joolswills** [comment]
I missed this PR - This should not be enabled by default - we used to enable it previously, but it breaks many games. mame4all standalone for the rpi has a structure that blacklists the asm z80 core and 68000 core for various games. 

In fact I actually disabled this in an earlier PR due to compatibility

see

https://github.com/libretro/mame2000-libretro/pull/22

**Comment by markwkidd** [comment]
> mame4all standalone for the rpi has a structure that blacklists the asm z80 core and 68000 core for various games

Thanks for checking in about this @joolswills . I would rather try to port the blacklist structure and take advantage of the greater performance when possible.

If you know where in the mame4all-pi source that is accomplished I would be grateful for a pointer, but I will take a look myself soon either way.

**Comment by joolswills** [comment]
Porting that over would work better - but in the meantime can we turn off drz80 by default ? Also the change doesn't reflect the build instructions now in https://github.com/libretro/mame2000-libretro/blob/master/readme.md - it might be useful to not turn them on by default, as even the cyclone core can have compatibility issues and on faster ARM cpus you probably don't want them on at all (which is why I switched them both off by default, but can be turned on via make params)

mame4all table is here

https://github.com/RetroPie/mame4all-pi/blob/master/src/rpi/gp2x_frontend_list.h

**Comment by markwkidd** [comment]
Given that you clearly know more about this than I do I'm fine with reversing the change. Do you want to submit the PR? I will have time over the next 24 hours but if you want to do it sooner please do.

@joolswills regardless of the PR could you please post about any other significant features from mame4all-pi you know of that ought to be ported to mame2000?

**Comment by joolswills** [comment]
I don't have time at present - just remove the two lines in the ifeq ARM bit and it should be fine.

I don't know of any features of mame4all apart from perhaps things like artwork etc. Don't know if mame2000 supports them or not.

**Comment by markwkidd** [comment]
https://github.com/libretro/mame2000-libretro/pull/52

**Pull request merged**
