### PR TITLE
Adds additional sound options

### PR DESCRIPTION
**Pull request by neonloop**

### CODE REVIEW

**Comment by grant2258** [comment]
This will cause issue with game like tapper ect without updating the audio code.

**Comment by neonloop** [comment]
@grant2258 isn't the behavior unchanged if the setting stays at default?

**Comment by grant2258** [comment]
yes its still an issue.

there are two things that can happen.
1) The memory isint allocated properly for the sound buffer in certain conditions.
2) the timing can be changed 

for the examples start tapper with 32000 listen it broken
again with tapper
set 44100 start tapper again its running far too fast. 

you need to restart after changing the sample rate.

**Comment by grant2258** [comment]
https://github.com/libretro/mame2000-libretro/blob/75c85fa07c1d4edc4fedfd3c4a6a10b39ffc2117/src/libretro/sound.c#L12-L38

https://github.com/libretro/mame2000-libretro/blob/75c85fa07c1d4edc4fedfd3c4a6a10b39ffc2117/src/mame.c#L93

**Comment by neonloop** [comment]
Yes, it was intended to require restart -- the option is only read in `retro_load_game`. Maybe there could still be a problem if a game is reloaded without reinitializing the core? I have not been able to test this because mame2000 will not run after unloading a game for me (`libco_quit` is set to 1 and never set back to 0)

I can continue to look into it, though...

**Comment by grant2258** [comment]
wget https://patch-diff.githubusercontent.com/raw/libretro/mame2000-libretro/pull/86.diff
git apply 86.diff

This segfaults most like causing your restart issues

**Pull request merged**
